Minor changes

diff --git a/install_hdf5 b/install_hdf5
--- a/install_hdf5
+++ b/install_hdf5
@@ -1,29 +1,34 @@
 #!/bin/bash
 
 export NAME="hdf5"
-export VERSION="1.8.20"
+export VERSION="1.10.4"
 source ./config
 
-fetch_http "https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-$VERSION.tar.gz"
-
-declare -a deps=( "mpich/3.2" )
+$fetch_http "https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-$VERSION.tar.gz"
+fetch_http "https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-$VERSION/src/hdf5-$VERSION.tar.gz"
+#declare -a deps=( "mpich/3.2" )
+declare -a deps=( "" )
 
 function build_script {
  cd hdf5-$VERSION
  module_load "${deps[@]}"
 
+ set -x
+ make clean
 ./configure --prefix="${PREFIX}" \
 	--enable-hl \
-	--enable-production \
+	--enable-build-mode=production \
 	--enable-fortran \
-	--enable-fortran2003 \
 	--enable-shared \
 	--enable-static \
-	--enable-parallel \
-	CC="mpicc" \
-	FC="mpif90" \
-	F77="mpi77" \
-	CXX="mpic++" || die "Couldn't configure"
+	--enable-parallel \ #not compatible with enable-cxx option
+    CC="$(which mpicc)" \
+    FC="$(which mpif90)" \
+    F77="$(which mpi77)" \
+    CXX="$(which mpic++)" || die "Couldn't configure"
+set +x
+
+	#--enable-cxx \
 
  make -j $THREAD_NUM || die "Couldn't make"
  make install  -j $THREAD_NUM || die "Couldn't install"
diff --git a/install_mdworkbench b/install_mdworkbench
--- a/install_mdworkbench
+++ b/install_mdworkbench
@@ -3,8 +3,8 @@
 export NAME="workbench"
 export VERSION="git"
 source ./config
-declare -a deps=("mpich/3.2"   "pcre/8.41" "glib/2.55.2" )
-
+#declare -a deps=("mpich/3.2"   "pcre/8.41" "glib/2.55.2" )
+declare -a deps=( )
 
 fetch_git "https://github.com/JulianKunkel/md-workbench.git"
 
@@ -18,10 +18,12 @@ function build_script {
  
 	${SRCdir}/configure \
 		--prefix=${PREFIX} \
-		--with-cc=$(which gcc) \
-		--minimal || die "configure failed"
+		--debug \
+		--with-cc=$(which gcc) || die "configure failed"
+		#--minimal || die "configure failed"
 		#--with-libs3="/mnt/lustre01/pf/k/k202107/software/install/libs3/git-20180711" || die "configure failed"
 
+		#--with-mpi="$(readlink -f $(dirname $(which mpiexec))/..)" \
 	set +x
  #cd "${SRCdir}"
 	cd build
