New scripts for mistral, netcdf-bench, python2 + several bug fixes

diff --git a/install_chevrotain b/install_chevrotain
--- a/install_chevrotain
+++ b/install_chevrotain
@@ -1,19 +1,17 @@
 #!/bin/bash
 
-export NAME="cherotain"
+export NAME="chevrotain"
 export VERSION="0.0.1"
 source ./config
 
-declare -a deps=( "mpich/3.2" "hdf5/1.8.20" "netcdf/4.5.0" "netcdf_fortran/4.4.4" "xios" "esmf/7.0.2" "psyclone/1.4.1" )
-#declare -a deps=( "mpich/3.2" "hdf5/1.8.20" "netcdf/4.5.0" "netcdf_fortran/4.4.4" "xios" "esmf/7.0.2"  )
+declare -a deps=( "mpich/3.2" "hdf5/1.8.20" "netcdf/4.5.0" "netcdf_fortran/4.4.4" "xios/svn-20180117" "esmf/7.0.2"  )
 
-fetch_local "/home/dkrz/k202107/software/downloads/chevrotain.tgz"
+fetch_local "/home/dkrz/k202107/software/downloads/chevrotain2.tgz"
 
 function build_script {
-  set -x
+  #set -x
 	cd chevrotain
 	module_load "${deps[@]}"
-	#mkdir -p build && cd build
 
 	#svn export --username <your_SRS_username> https://code.metoffice.gov.uk/svn/lfric/LFRic/tags/chevrotain
 	#(supply password when prompted)
@@ -24,22 +22,32 @@ function build_script {
 	export FC=gfortran
 	export FPP=cpp
 	export LDMPI=mpif90
-	BUILD_DIR="/home/dkrz/k202107/software/cache/xios/svn-20180110"
+	#BUILD_DIR="/home/dkrz/k202107/software/cache/xios/svn-20180117"
+	exists xios_server.exe
+	BUILD_DIR="$(readlink -f $(dirname $(which xios_server.exe))/..)"
 
-	export FFLAGS="-I$BUILD_DIR/inc -I$ESMFDIR/mod/modO/Linux.gfortran.64.mpich2.default -I$INSTALL_DIR/include"
-	export LDFLAGS="-L$BUILD_DIR/lib -L$ESMFDIR/lib/libO/Linux.gfortran.64.mpich2.default -L$INSTALL_DIR/lib"
-	export CPPFLAGS="-I$ESMFDIR/mod/modO/Linux.gfortran.64.mpich2.default -I$INSTALL_DIR/include"
-	export LD_LIBRARY_PATH="$INSTALL_DIR/lib:$INSTALL_DIR/lib64:$ESMFDIR/lib/libO/Linux.gfortran.64.mpich2.default"
+	ADD_INC=$(find $INSTALL_ROOT_DIR -maxdepth 3 -type d -regextype posix-egrep -regex ".*/include" -printf "-I/$%h/include ")
+	ADD_LIB=$(find $INSTALL_ROOT_DIR -maxdepth 3 -type d -regextype posix-egrep -regex ".*/lib" -printf "-L/$%h/lib ")
+	ADD_LIB+=$(find $INSTALL_ROOT_DIR -maxdepth 3 -type d -regextype posix-egrep -regex ".*/lib64" -printf "-L/$%h/lib64 ")
 
-	sed -i "s/export EXTERNAL_STATIC_LIBRARIES += xios.*/export EXTERNAL_STATIC_LIBRARIES += xios stdc++ netcdf_c++ netcdff netcdf esmf/" Makefile
+	export FFLAGS="-I$BUILD_DIR/inc -I$ESMFDIR/mod/modO/Linux.gfortran.64.mpich2.default $ADD_INC"
+	export LDFLAGS="-L$BUILD_DIR/lib -L$ESMFDIR/lib/libO/Linux.gfortran.64.mpich2.default $ADD_LIB"
+	export CPPFLAGS="-I$ESMFDIR/mod/modO/Linux.gfortran.64.mpich2.default $ADD_INC"
+	export LD_LIBRARY_PATH="$ESMFDIR/lib/libO/Linux.gfortran.64.mpich2.default:$LD_LIBRARY_PATH"
+
+	sed -i "s/.*trim.*)\s*$/&, \&/" gungho/working/gungho/algorithm/solver_mod.x90
+	sed -i "s/export EXTERNAL_STATIC_LIBRARIES = xios.*/export EXTERNAL_STATIC_LIBRARIES = xios stdc++ netcdff netcdf esmf/" gungho/Makefile
 
 	cd gungho
-	make build
+	make VERBOSE=1 build  || die "Couldn't build"
 	#cd example
 
+	echo "You may want to run:"
+	echo "../../bin/gungho gungho_configuration.nml"
+	echo "mpiexec -np 6 ../../bin/gungho gungho_configuration.nml"
 
 	#../bin/gungho gungho_configuration.nml
-	set +x
+	#set +x
 }
 
 build_with build_script
@@ -47,4 +55,3 @@ build_with build_script
 module_init
 module_deps "${deps[@]}"
 auto_module_paths
-add_prepend_path "$MFILE" "C_INCLUDE_PATH" "include/fuse3"
