nai

diff --git a/install_hdf5 b/install_hdf5
--- a/install_hdf5
+++ b/install_hdf5
@@ -1,15 +1,23 @@
 #!/bin/bash
 
 export NAME="hdf5"
-export VERSION="1.10.5"
+export VERSION="1.12.0"
 source ./config
 
-fetch_http "https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-$VERSION/src/hdf5-$VERSION.tar.gz"
+#fetch_http "https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-$VERSION/src/hdf5-$VERSION.tar.gz"
+fetch_http "https://hdf-wordpress-1.s3.amazonaws.com/wp-content/uploads/manual/HDF5/HDF5_1_12_0/source/hdf5-1.12.0.tar.gz"
 
-declare -a deps=( "" )
+declare -a load=( \
+  "cmake/3.19.5" \
+)
+declare -a deps=( \
+  "openmpi/4.1.0" \
+  "szip/2.1" \
+)
 
 function build_script {
  cd hdf5-$VERSION
+ module_load "${load[@]}"
  module_load "${deps[@]}"
 
  set -x
@@ -21,16 +29,18 @@ function build_script {
 	--enable-shared \
 	--enable-static \
 	--enable-parallel \
+  --with-default-api-version=v18 \
+  --with-szlib=${SZIP_DIR} \
     CC="$(which mpicc)" \
     FC="$(which mpif90)" \
     F77="$(which mpi77)" \
-    CXX="$(which mpic++)" || die "Couldn't configure"
+    CXX="$(which mpic++)" || die "configure failed"
 set +x
 
 	#--enable-cxx \
 
- make -j $THREAD_NUM || die "Couldn't make"
- make install  -j $THREAD_NUM || die "Couldn't install"
+ make -j $THREAD_NUM || die "make failed"
+ make install  -j $THREAD_NUM || die "install failed"
 }
 
 build_with build_script
diff --git a/install_netcdf b/install_netcdf
--- a/install_netcdf
+++ b/install_netcdf
@@ -1,20 +1,28 @@
 #!/bin/bash
 
 export NAME="netcdf"
-export VERSION="4.6.1"
+export VERSION="4.8.0"
 source ./config
 
-fetch_http "ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-$VERSION.tar.gz"
+fetch_http "https://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-c-4.8.0.tar.gz"
 
-#declare -a deps=( "mpich/3.2" "hdf5/1.8.20" )
-declare -a deps=( "hdf5/1.10.5" )
+declare -a load=( \
+  "cmake/3.19.5" \
+)
+
+declare -a deps=( \
+  "openmpi/4.1.0" \
+  "szip/2.1" \
+  "maee/hdf5/1.12.0" \
+)
 
 function build_script {
-	set -x
- cd netcdf-$VERSION
+	#set -x
+ cd netcdf-c-$VERSION
+ module_load "${load[@]}"
  module_load "${deps[@]}"
+ module list
 
- exists h5dump
  CC=$(which mpicc) 
  CXX=$(which mpicxx)
  FF=$(which mpif90)
@@ -23,18 +31,20 @@ function build_script {
  MPIDIR="$(readlink -f $(dirname $(which mpiexec))/..)"
  H5DIR="$(readlink -f $(dirname $(which h5dump))/..)"
  #export LDFLAGS="-L${H5DIR}/lib -Wl,--rpath=${H5DIR}/lib"
- export LDFLAGS="-L${H5DIR}/lib"
+ export LDFLAGS="-L${H5DIR}/lib64"
  export CPPFLAGS="-I${H5DIR}/include -I${MPIDIR}/include"
  export CFLAGS=""
 
-./configure \
- --prefix=${PREFIX} \
- --enable-shared \
- --enable-static || die "Couldn't configure"
+ make clean
+ ./configure \
+   --prefix=${PREFIX} \
+   --enable-shared \
+   --enable-static || die "Couldn't configure"
 
- make -j $THREAD_NUM || die "Couldn't make"
- make install  -j $THREAD_NUM || die "Couldn't install"
- set +x
+
+  make -j $THREAD_NUM || die "Couldn't make"
+  make install  -j $THREAD_NUM || die "Couldn't install"
+  set +x
 }
 
 build_with build_script
