Major update

diff --git a/install_ior b/install_ior
--- a/install_ior
+++ b/install_ior
@@ -13,20 +13,21 @@ function build_script {
     set -x
     make clean
 
-    export C_INCLUDE_PATH="$C_INCLUDE_PATH:/usr/include"
-    export LDFLAGS="-Wl,-rpath=${MPIDIR}/lib -L${MPIDIR}/lib -L${H5DIR}/lib -lgpfs" 
-    export CPPFLAGS="-I${MPIDIR}/include -I${H5DIR}/include -I/usr/include"
+    #export C_INCLUDE_PATH="$C_INCLUDE_PATH:/usr/include"
+    #export LDFLAGS="-Wl,-rpath=${MPIDIR}/lib -L${MPIDIR}/lib -L${H5DIR}/lib -lgpfs" 
+    #export CPPFLAGS="-I${MPIDIR}/include -I${H5DIR}/include -I/usr/include"
 
     ./configure \
         --prefix="${PREFIX}" \
-        --with-ime \
         --with-posix \
-        --with-mpiio 
-        # --with-lustre 
+        --with-mpiio || die "Configure failed"
+
+        #--with-lustre \
+        #--with-ime \
 
     set +x
-    make -j${THREAD_NUM}
-    make install
+    make -j${THREAD_NUM} || die "Make failde"
+    make install || die "Install failed"
 }
 
 
diff --git a/install_python3 b/install_python3
--- a/install_python3
+++ b/install_python3
@@ -1,32 +1,40 @@
 #!/bin/bash
 
 export NAME="python"
-export VERSION="3.6.4"
+export VERSION="3.8.0"
 source ./config
 
-fetch_http "https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tgz"
+fetch_http "https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz"
 
-declare -a deps=( )
+declare -a deps=( "xz/5.2.4" "sqlite/3300100" )
 #declare -a deps=( "mpich/3.2" "hdf5/1.8.20" "netcdf/4.5.0" "netcdf_fortran/4.4.4" )
 
 function build_script {
+	cd Python-3.8.0
+	module_load "${deps[@]}"
+
+    set -x
 	SSLDIR="$(readlink -f $(dirname $(which openssl))/..)"
-	cd Python-3.6.4 
+	XZDIR="$(readlink -f $(dirname $(which xz))/..)"
+	SQL="$(readlink -f $(dirname $(which sqlite3))/..)"
 	export CC="$(which gcc)"
 	export CXX="$(which g++)"
-	export LDFLAGS="-L$SSLDIR/lib"
-	export CPPFLAGS="-I$SSLDIR/include"
-	export CFLAGS="-I$SSLDIR/include"
+	export LDFLAGS="$LDFLAGS -L$SSLDIR/lib -L$XZDIR/lib -L$SQL/lib"
+	export CPPFLAGS="$CPPFLAGS -I$SSLDIR/include -I$XZDIR/include -I$SQL/include"
+	export CFLAGS="$CFLAGS -I$SSLDIR/include -I$XZDIR/include -I$SQL/include"
 	#export CPPFLAGS="-ggdb -O0"
 	#export CFLAGS="-ggdb -O0"
 	#./configure --prefix=$PREFIX --with-pydebug --with-valgrind
 	./configure \
 		--prefix=$PREFIX \
-		--with-ensurepip=install
+        --enable-loadable-sqlite-extensions \
+        --enable-shared \
+		--with-ensurepip=install || die "Couldn't configure"
 	#--with-valgrind \
 
-	make -j${THREAD_NUM}
-	make install
+	make -j${THREAD_NUM} || die "Couldn't make"
+	make install || die "Couldn't install"
+    set +x
 }
 
 build_with build_script
diff --git a/install_xz b/install_xz
--- a/install_xz
+++ b/install_xz
@@ -1,21 +1,19 @@
 #!/bin/bash
 
-export NAME="glib"
-export VERSION="2.56.4"
+export NAME="xz"
+export VERSION="5.2.4"
 source ./config
 
-fetch_http "http://ftp.acc.umu.se/pub/GNOME/sources/glib/2.56/glib-2.56.4.tar.xz"
-
-declare -a deps=( "pcre/8.44" "python/2.7.15" )
+fetch_http "https://tukaani.org/xz/xz-5.2.4.tar.xz"
+declare -a deps=(  )
 
 function build_script {
 	set -x
-	cd glib-$VERSION
+	cd xz-$VERSION
 	module_load "${deps[@]}"
 
 	./configure \
-		--prefix=${PREFIX} \
-		--disable-libmount || die "Couldn't configure"
+		--prefix=${PREFIX}  || die "Couldn't configure"
 
 	make -j $THREAD_NUM || die "Couldn't make"
 	make install  -j $THREAD_NUM || die "Couldn't install"
